
/*
 * 
 */

package com.mycompany.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.1
<<<<<<< HEAD
 * Thu Aug 16 17:28:22 COT 2012
=======
 * Tue Jul 24 16:58:04 COT 2012
>>>>>>> 74eea3a6b3d863bb64df89d620e35f3a4c36de2a
 * Generated source version: 2.2.1
 * 
 */


@WebServiceClient(name = "PersonaServiceImplService", 
<<<<<<< HEAD
                  wsdlLocation = "http://localhost:8086/wspersona/PersonaService?wsdl",
=======
                  wsdlLocation = "http://localhost:8087/wspersona/PersonaService?wsdl",
>>>>>>> 74eea3a6b3d863bb64df89d620e35f3a4c36de2a
                  targetNamespace = "http://servicio.mycompany.com/") 
public class PersonaServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://servicio.mycompany.com/", "PersonaServiceImplService");
    public final static QName PersonaServiceImplPort = new QName("http://servicio.mycompany.com/", "PersonaServiceImplPort");
    static {
        URL url = null;
        try {
<<<<<<< HEAD
            url = new URL("http://localhost:8086/wspersona/PersonaService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8086/wspersona/PersonaService?wsdl");
=======
            url = new URL("http://localhost:8087/wspersona/PersonaService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8087/wspersona/PersonaService?wsdl");
>>>>>>> 74eea3a6b3d863bb64df89d620e35f3a4c36de2a
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PersonaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonaServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PersonaService
     */
    @WebEndpoint(name = "PersonaServiceImplPort")
    public PersonaService getPersonaServiceImplPort() {
        return super.getPort(PersonaServiceImplPort, PersonaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonaService
     */
    @WebEndpoint(name = "PersonaServiceImplPort")
    public PersonaService getPersonaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PersonaServiceImplPort, PersonaService.class, features);
    }

}
